import { Bounty, LocalContext } from '../types';

export const mockBounties: Bounty[] = [
  {
    id: 'b1',
    merchantName: 'Bäckerei Frank',
    merchantType: 'bakery',
    maxDiscountPercentage: 15,
    rules: ['Target users walking slowly (browsing)', 'Offer warm drinks and pastries if weather is cold or overcast', 'Emphasize that we have a fresh batch brewed'],
    status: 'active',
    targetDensity: 'low',
  },
  {
    id: 'b2',
    merchantName: 'Kaufhaus Mitte',
    merchantType: 'retail',
    maxDiscountPercentage: 20,
    rules: ['Target users strolling near the Königsstraße shopping district', 'Push umbrella sales if raining'],
    status: 'active',
    targetDensity: 'medium',
  },
  {
    id: 'b3',
    merchantName: 'VVS Stuttgart (Transit)',
    merchantType: 'transit',
    maxDiscountPercentage: 100,
    rules: ['Offer free short-distance ticket if it is raining heavily', 'Target users far from home'],
    status: 'inactive',
  },
  {
    id: 'b4',
    merchantName: 'SchwabenBräu Gaststätte',
    merchantType: 'restaurant',
    maxDiscountPercentage: 30,
    rules: ['Offer lunch deals between 11:30 and 13:30', 'Target groups if density is high'],
    status: 'active',
    targetDensity: 'low',
  },
  {
    id: 'b5',
    merchantName: 'Breuninger Flagship',
    merchantType: 'retail',
    maxDiscountPercentage: 10,
    rules: ['Target users strolling on weekends', 'Push VIP lounge access if battery is high'],
    status: 'active',
    targetDensity: 'high',
  },
  {
    id: 'b6',
    merchantName: 'TIER E-Scooters',
    merchantType: 'transit',
    maxDiscountPercentage: 50,
    rules: ['Target commuters walking fast', 'Offer 50% off unlock fee if it starts raining'],
    status: 'active',
    targetDensity: 'medium',
  }
];

export const mockContexts: LocalContext[] = [
  {
    batteryLevel: 82,
    walkingSpeed: 'browsing',
    weather: 'cloudy',
    temperatureC: 11,
    timeOfDay: '12:48',
    transactionDensity: 'low',
    localEvents: [],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 15,
    walkingSpeed: 'commuting',
    weather: 'raining',
    temperatureC: 8,
    timeOfDay: '14:30',
    transactionDensity: 'low',
    localEvents: ['Cannstatter Volksfest Setup'],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 60,
    walkingSpeed: 'browsing',
    weather: 'sunny',
    temperatureC: 22,
    timeOfDay: '12:00',
    transactionDensity: 'high',
    localEvents: ['Karlsplatz Flea Market'],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 12,
    walkingSpeed: 'commuting',
    weather: 'snowing',
    temperatureC: -2,
    timeOfDay: '23:15',
    transactionDensity: 'low',
    localEvents: ['VfB Stuttgart Night Game Ending'],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 60,
    walkingSpeed: 'browsing',
    weather: 'sunny',
    temperatureC: 22,
    timeOfDay: '12:00',
    transactionDensity: 'high',
    localEvents: ['Karlsplatz Flea Market'],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 98,
    walkingSpeed: 'stationary',
    weather: 'sunny',
    temperatureC: 18,
    timeOfDay: '09:30',
    transactionDensity: 'high',
    localEvents: ['Trade Fair: Messe Stuttgart'],
    city: 'Stuttgart, DE',
  },
  {
    batteryLevel: 25,
    walkingSpeed: 'commuting',
    weather: 'raining',
    temperatureC: 9,
    timeOfDay: '08:15',
    transactionDensity: 'medium',
    localEvents: ['University Semester Start'],
    city: 'Heidelberg, DE',
  },
  {
    batteryLevel: 88,
    walkingSpeed: 'browsing',
    weather: 'sunny',
    temperatureC: 24,
    timeOfDay: '14:00',
    transactionDensity: 'high',
    localEvents: ['Cologne Cathedral Tours'],
    city: 'Cologne, DE',
  },
  {
    batteryLevel: 10,
    walkingSpeed: 'commuting',
    weather: 'cloudy',
    temperatureC: 5,
    timeOfDay: '02:30',
    transactionDensity: 'low',
    localEvents: ['Berghain Line / Club District'],
    city: 'Berlin, DE',
  },
  {
    batteryLevel: 75,
    walkingSpeed: 'stationary',
    weather: 'raining',
    temperatureC: 12,
    timeOfDay: '19:00',
    transactionDensity: 'high',
    localEvents: ['Fitness Expo'],
    city: 'Frankfurt, DE',
  }
];
